project:
  type: book

book:
  title: "datascience2: Prädiktive Modelle auf Basis von Textdaten"
  author: "Sebastian Sauer"
  date: "9/13/2022"
  chapters:
    - index.qmd
    - twittermining.qmd
    - references.qmd

bibliography: references.bib

lang: de

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: source

