project:
  type: book
  


book:
  title: "Data Science 2: Textdaten als Grundlage prädiktiver Modelle"
  author: "Sebastian Sauer"
  date: "9/13/2022"
  chapters:
    - index.qmd
    - pruefung.qmd
    - twittermining.qmd
    - textmining1.qmd
    - populismus.qmd
    - word-embedding.qmd
    - hassrede.qmd
    - klassifikation.qmd
    - references.qmd

bibliography: references.bib

lang: de

format:
  html:
    theme: cerulean
    df-print: kable
    code-fold: false
    toc: true
  # pdf:
  #   documentclass: scrreprt

editor: source
keep-md: false

knitr: 
  opts_chunk: 
    fig-align: center
    out-width: "70%"

    
execute:
  freeze: auto
  cache: true
