project:
  type: book
  
book:
  title: "Data Science 2: Textdaten als Grundlage prädiktiver Modelle 📚🔮"
  author: "Sebastian Sauer"
  date: now
  chapters:
    - part: Organisatorisches
      chapters:
        - index.qmd
        - 010-Hinweise.qmd
        - 020-pruefung.qmd
    - part: Textmining
      chapters:
        - 025-twittermining.qmd
        - 030-textmining1.qmd
        - 040-populismus.qmd
        - 065-Information.qmd 
        - 050-word-embedding.qmd
        - 060-hassrede.qmd
        - 067-miniprojekt1.qmd
    - part: Tidymodels
      chapters:
        - 080-klassifikation.qmd
        - 070-hatespeech2.qmd
        - 095-miniprojekt2.qmd
    - part: Deep Learning
      chapters:
        - 105-python-r.qmd
        - 100-nn-quickstart.qmd
        - 110-nn-theo1.qmd
        - 120-transformer.qmd
    - part: Anwendung
      chapters: 
        - 200-projektmgt.qmd
        - 300-fallstudien.qmd
    - part: Abschluss
      chapters:
        - references.qmd

bibliography: 
  - bib/bib.bib
  - packages.bib


lang: de

format:
  html:
    toc: true
    theme: 
      light: [lumen, my-theme.scss]
      dark: darkly
    css: styles.css
    number-sections: true
    df-print: paged
    code-fold: false
    fig-align: center
    code-link: true
    mermaid:
      theme: neutral

editor: source
keep-md: false

knitr:
  opts_knit:
    verbose: true
    fig-align: center
  opts_chunk:
    collapse: true
    # comment: "#>"
    R.options:
      knitr.graphics.auto_pdf: false

    
execute:
  freeze: auto
  cache: true
