


<!-- ## Prüfungsform Datenanalyse -->


Alle folgenden Hinweise gelten nur insoweit Ihre Lehrkraft Ihnen keine anders lautenden Hinweise gegeben hat (schriftlich).




## Allgemeines


1. Gegenstand dieser Prüfungsform ist eine Projektarbeit in Form von *Analyse* eines Datensatzes nach einer *Forschungsfrage* und die *Dokumentation* dieser Analyse.


4. Schreiben Sie Ihre Datenanalyse in Form eines *Berichts*, der sich an den Gliederungspunkten wie unten dargestellt orientiert.

5. Wenden Sie die passenden, im Unterricht eingeführten, *statistischen Verfahren* an. Es steht Ihnen frei, andere (nicht im Unterricht behandelte) Verfahren zur Analyse der Daten anzuwenden, nach Maßgabe der fachlichen Angemessenheit.

6. Werten Sie die Daten mit *R* oder *Python* aus.

7. Die *R-Syntax* soll im Hauptteil des Berichts dokumentiert werden. R-Output darf ggf. gekürzt wiedergegeben werden.

9. Fügen Sie *keine Erklärungen* oder Definitionen von statistischen Verfahren an.

10. *Beschreiben* und *interpretieren* Sie jede Analyse bzw. jeden R-Code bzw. jedes Ergebnis (jede R-Ausgabe).

11. Von hoher Bedeutung ist die *Korrektheit* der Beschreibung und Interpretation der *statistischen Modellierung* (z.B. mit der Regressionsanalyse).

12. Es hat *keinen Einfluss* auf Ihre Note, ob sich ein (erwarteter) *Effekt* zeigt und wie stark dieser Effekt ggf. ist.

13. Zu Beginn der Analyse müssen folgende *Metadaten* *gut ersichtlich* platziert sein (z.B. auf einem Deckblatt):
 
 - Vorname Nachname der Autors/der Autorin
 - Matrikelnummer
 - Modulname
 - Abgabedatum


14. Die *Abgabefrist endet mit Verstreichen des regulären Prüfungszeitraums* (soweit nicht vom Prüfer anderweitig angegeben).

15. Studentis mit *Nachteilsausgleich* melden sich beim Prüfer und zeigen ihren Antrag auf Nachteilsausgleich an.


## Einzureichende Dateien

1. Einzureichen sind folgende Dateien:

  a. der Bericht in menschenlesbarer Form (s. Formatierungshinweise)
  b. alle Dateien, die Quellcode der Analyse beinhalten. 
  c. die Rohdaten
  
2. Der Name der Dateien kann frei gewählt werden (bzw. folgt keinen technischen Restriktionen).



## Formatierung des Berichts

1. Der Bericht ist *nur elektronisch*, nicht ausgedruckt einzureichen.

2. Der Bericht kann in einem *paginierten Format* (z.B. Word)  oder einem *nicht-paginierten* Format (HTML-Dokument) verfasst werden. Abzugeben ist aber eine PDF-Datei oder eine HTML-Datei, die alle Bilder und sonstige Medien enthält ("Stand-Alone-HTML").


4. Die Wahl eines bestimmten Stylesheets ist nicht von Bedeutung. *Lesbarkeit* und *Übersichtlichkeit* in der Formatierung sind unabhängig davon anzustreben.

5. Im *Kopfbereich* (oder auf einem Deckblatt) sind die relevanten *Metadatan* anzugeben wie Name (Nachname, Vorname) der Autorin/des Autors, Abgabedatum, Titel der Arbeit, Modul.



## Formalia

1. Richtlinien einer *Wortzahl* gibt es nicht. Entscheidend ist, dass relevante Analysen durchgeführt und beschrieben wurden. Schreiben Sie so knapp wie möglich und so ausführich wie nötig.

2. Der *Anspruch* richtet sich nach dem Inhalt und Niveau des auf diese Prüfung vorbereitenden Unterricht (auch aus Modulen vorheriger Semester). Oft sind das Module in quantitativer Datenanalyse (und wissenschaftliches Arbeiten). Deren Inhalte sollen im Rahmen dieser Prüfungsleistung als selbständig und flüssig verfügbare Kompetenz von den Studentis demonstriert werden.

3. Die *Gliederung* der Arbeit kann sich an den [PPDAC-Zyklus](https://stats-nutshell.netlify.app/basics.html#ppdac) und am [Data Science Model von Wickham und Grolemund](https://r4ds.had.co.nz/introduction.html#what-you-will-learn) orientieren.







## Beurteilungskriterien


Die Arbeit wird im Hinblick auf *drei Kriterien* bewertet:

1. *Formalia* (z. B. Vollständigkeit der Abarbeitung, Angemessenheit der äußeren Gestaltung, Fokus auf Wesentliche, Übersichtlichkeit, Ästhetik, Reproduzierbarkeit)

2. *Methodik* (z. B. Richtige Auswahl und Anwendung der Verfahren, methodisches Verständnis)

3. *Inhalt* (z. B. Verständlichkeit, Breite und Tiefe der Problemlösung, Korrektheit der Interpretation)




Sie erhalten für jedes der drei Kriterien eine Teilnote sowie eine Gesamtnote. Außerdem erhalten Sie ggf. für die Kriterien noch ausformulierte Hinweise.

Die Gesamtnote muss sich *nicht* als Mittelwert der Teilnoten ergeben.

Insbesondere kann eine Fünf in einem der Kriterien zum Durchfallen führen, auch wenn die anderen beiden Kriterien gut oder sehr gut beurteilt wurden.





## Beispiele für Aspekte der Beurteilungskriterien


1. Wurden deskriptive Statistiken (an angemessenen Ort) berichtet?

2. Wurden Diagramme und Tabellen angemessen eingesetzt?

3. Wurde Inferenzstatistik (angemessen) eingesetzt?

5. Wurden Effektstärkemaße (idealerweise mit Konfidenzintervallen dazu) berichtet?

6. Wurden alle relevanten Informationen für ein statistisches Verfahren angegeben (z.B. zum gewählten Prior)?

7. Wurde die Aussagekraft von Modellergebnissen richtig eingeschätzt?

8. Waren die Schlussfolgerungen, die aus den statistischen Ergebnissen gezogen wurden, angemessen (z. B. wurde erkannt, dass ein Nicht-Verwerfeen einer Hypothese nicht automatisch ein Bestätigen derselben bedeutet)?

9. Wurde angemessen gerundet (inkl. konsistente Anzahl von Nachkommastellen)?

10. Passen die statistischen Verfahren zu den Hypothesen?

11. Wurden die Voraussetzungen der statistischen Verfahren geprüft?

12. Sind die Ergebnisse reproduzierbar (Daten und Syntax eingereicht)?



## Beispiele für Fehler


Schwere Fehler, die zum Durchfallen oder deutlichem Abwerten der Note führen können, sind z.B.:

- fehlende Inferenzstatistik (oder adäquatem Ersatz)
- falsche Interpretation von Posteriori-Verteilungen oder p-Werten
- keine Angabe von Konfidenzintervallen 
- falsche Interpretation von Konfidenzintervallen
- Wahl des falschen Intervalls (Vorhersageintervall vs. Perzentilintervall vs. HDI)
- falsche Entscheidung zum Hypothesentest auf Basis entsprechender Kennwerte (wie ROPE-Wahrscheinlichkeit oder p-Wert) 
- falsche Wahl des statistischen Verfahrens 
- fehlende Deskriptivstatistik



Häufige kleinere Mängel sind z. B.

- pixelige Abbildungen 
- R-Ausgaben oder R-Syntax als Screenshot 
- fehlende Seitenzahlen (nur bei paginierten Formaten, nicht bei HTML) 
- unübersichtliche Diagramme 
- kein (verlinktes) Inhaltsverzeichnis ︎
- fehlende oder unverständliche Achsenbeschriftung bei Diagrammen 
- fehlende oder falsche Beschreibung der/des Skalenniveau(s) der untersuchten Variablen


## Sonstiges


Eine automatische Prüfung auf Plagiate mittels geeigneter, von der Hochschule bereitgestellter Software ist möglich.




